//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    using Repository.Pattern.Ef6;
    using Newtonsoft.Json;
    public partial class AuthTokens : Entity
    {
        public int TokenID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string Token { get; set; }
        public System.DateTime IssuedOn { get; set; }
        public System.DateTime ExpiresOn { get; set; }
    
    	[JsonIgnore]
        public virtual Accounts Accounts { get; set; }
    	[JsonIgnore]
        public virtual Employees Employees { get; set; }
    }
}
